/**
 * UsersAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostViewModel } from './postViewModel';

export interface UserViewModel { 
    id?: number;
    name?: string;
    dob?: Date;
    posts?: Array<PostViewModel>;
}